title: Chester Tan
url: https://chester-tan.com
theme: jekyll-theme-hacker

plugins:
    - jekyll-feed

chester_tan:
    name: Chester Tan
    email: mail@chester-tan.com
    web: https://chester-tan.com
